application: foobnix-gae-cms
version: 2
runtime: python
api_version: 1

handlers:

- url: /jwysiwyg
  static_dir: resources/jwysiwyg

- url: /css
  static_dir: resources/css
 
- url: /js
  static_dir: resources/js
 
- url: /images
  static_dir: resources/images

- url: /.*
  script: main.py
