application: marinatext
version: 4
runtime: python
api_version: 1

handlers:

- url: /static
  static_dir: administrator/templates/default/static

- url: /css
  static_dir: templates/marina/css
 
- url: /js
  static_dir: templates/marina/js
 
- url: /images
  static_dir: templates/marina/images
 
- url: /custom_url
  script: cms/tasks/task.py
  login: required
  

- url: /.*
  script: main.py
  
builtins:
- datastore_admin: on  

inbound_services:
- mail