application: foobnix-cms
version: 14
runtime: python
api_version: 1

handlers:

- url: /static
  static_dir: administrator/templates/default/static

- url: /css
  static_dir: templates/foobnix-cms/css
 
- url: /js
  static_dir: templates/foobnix-cms/js
 
- url: /images
  static_dir: templates/foobnix-cms/images

- url: /.*
  script: main.py
  
  
builtins:
- datastore_admin: on  

inbound_services:
- mail