application: foobnix-gae-cms
version: 2
runtime: python
api_version: 1

handlers:

- url: /jwysiwyg-color
  static_dir: administrator/templates/default/jwysiwyg-color

- url: /css
  static_dir: templates/default/css
 
- url: /js
  static_dir: templates/default/js
 
- url: /images
  static_dir: templates/default/images

- url: /.*
  script: main.py
