application: foobnix-cms
version: 1
runtime: python
api_version: 1

handlers:

- url: /css
  static_dir: resources/css
 
- url: /js
  static_dir: resources/js
 
- url: /images
  static_dir: resources/images

- url: /.*
  script: web/main.py
