application: marina
version: 1
runtime: python
api_version: 1

handlers:

- url: /static
  static_dir: administrator/templates/default/static

- url: /css
  static_dir: templates/marina/css
 
- url: /js
  static_dir: templates/marina/js
 
- url: /images
  static_dir: templates/marina/images

- url: /.*
  script: main.py
  
  
builtins:
- datastore_admin: on  

inbound_services:
- mail